name: PR Template

on:
  pull_request:
    types: [opened, synchronize, ready_for_review]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
         bun-version: 1.0.21

    - name: Install dependencies
      run: bun install

    - name: Build application
      run: bun run build

    - name: Run tests
      run: bun test
